"use client"

/**
 * Activate Account form — luxury membership-pass card.
 * -----------------------------------------------------
 * Collects the three identity fields required to activate a Quotex Live
 * account, validates them in real time, and on submit looks the QXL key
 * up in Firebase. If the key was generated by an admin and is still
 * available (status="unused"), we flip it to "used" with the holder's
 * name + username and redirect to the personal profile dashboard at
 * /profile/{key}. From there the signal rooms become reachable
 * (chart-to-signal, chart-15sec-signal, chart-2candle).
 *
 * If the key is already activated by the same username we let them back
 * in (re-entry case). Anything else shows an inline error.
 *
 * Validation rules
 * - Full Name : 4–14 characters, any character allowed (incl. spaces & symbols)
 * - Username  : 4–8 characters, [A–Z a–z 0–9 _] only (underscore allowed,
 *               no spaces, no other symbols)
 * - QXL Key   : non-empty (free-form)
 *
 * Visual treatment is deliberately premium:
 *  - Card framed with corner accents, top member strip, soft outer halo
 *  - Each field icon sits inside a gradient teal puck (not flat fill)
 *  - Inputs use subtle inset shadow + animated focus ring
 *  - Submit button keeps the continuous shine + breathing pulse from the
 *    home page hero so the CTA feels consistent.
 */

import { useRouter } from "next/navigation"
import { useEffect, useMemo, useState, type ChangeEvent, type FormEvent } from "react"
import { get, ref, serverTimestamp, set, update } from "firebase/database"
import {
  ArrowRight,
  BadgeCheck,
  CheckCircle2,
  AtSign,
  IdCard,
  KeySquare,
  Loader2,
  Unlock,
} from "lucide-react"

import { useLanguage } from "@/components/language-provider"
import {
  generateAccessToken,
  generateDeviceId,
  writeClientSession,
} from "@/lib/access-tokens"
import { getDb } from "@/lib/firebase"
import { asTier } from "@/lib/tiers"
import { cn } from "@/lib/utils"

// Validation thresholds — kept inline so the rules stay obvious to readers.
const FULL_NAME_MIN = 4
const FULL_NAME_MAX = 14
const USERNAME_MIN = 5
const USERNAME_MAX = 32
const USERNAME_RE = /^[A-Za-z0-9_]*$/

type FieldError = string | null
type Errors = {
  fullName: FieldError
  username: FieldError
  qxlKey: FieldError
}
const NO_ERRORS: Errors = { fullName: null, username: null, qxlKey: null }

export function ActivateAccountForm() {
  const { t } = useLanguage()
  const router = useRouter()

  const [fullName, setFullName] = useState("")
  const [username, setUsername] = useState("")
  const [qxlKey, setQxlKey] = useState("")
  const [touched, setTouched] = useState<Record<keyof Errors, boolean>>({
    fullName: false,
    username: false,
    qxlKey: false,
  })
  const [submitting, setSubmitting] = useState(false)
  /**
   * Server-side error from the Firebase activation lookup. We surface
   * this *under* the QXL key field so it reads naturally as feedback on
   * the value the user just typed.
   */
  const [activationError, setActivationError] = useState<string | null>(null)
  const [success, setSuccess] = useState<null | {
    name: string
    username: string
    qxlKey: string
    /** Random session credential — what the redirect URL uses. */
    accessToken: string
  }>(null)

  // Pure validator — runs on every render so error display stays in sync.
  const errors = useMemo<Errors>(() => {
    const e: Errors = { ...NO_ERRORS }

    const trimmedName = fullName.trim()
    if (trimmedName.length > 0 && trimmedName.length < FULL_NAME_MIN)
      e.fullName = t("activate.form.fullName.errorMin")
    else if (trimmedName.length > FULL_NAME_MAX)
      e.fullName = t("activate.form.fullName.errorMax")

    if (username.length > 0 && !USERNAME_RE.test(username))
      e.username = t("activate.form.username.errorFormat")
    else if (username.length > 0 && username.length < USERNAME_MIN)
      e.username = t("activate.form.username.errorMin")
    else if (username.length > USERNAME_MAX)
      e.username = t("activate.form.username.errorMax")

    return e
  }, [fullName, username, t])

  const isValid =
    fullName.trim().length >= FULL_NAME_MIN &&
    fullName.trim().length <= FULL_NAME_MAX &&
    username.length >= USERNAME_MIN &&
    username.length <= USERNAME_MAX &&
    USERNAME_RE.test(username) &&
    qxlKey.trim().length > 0

  /**
   * Look up the QXL key in Firebase, claim it for this holder if it's
   * unused, then mint a fresh access token + deviceId pair, persist
   * them in RTDB / localStorage / cookies, and forward to
   * `/profile/{accessToken}`. Re-entry by the same username from a new
   * browser is allowed — we mint a brand-new token, which silently
   * revokes the previous browser's access (the previous browser's
   * deviceId stops matching the one stored in Firebase). Any other
   * state (key not found, claimed by a different username, RTDB error)
   * becomes an inline error message.
   */
  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setTouched({ fullName: true, username: true, qxlKey: true })
    setActivationError(null)
    if (!qxlKey.trim()) return
    if (!isValid) return

    const cleanedName = fullName.trim()
    const cleanedUser = username.trim()
    const cleanedKey = qxlKey.trim()

    setSubmitting(true)
    try {
      // Direct path lookup — admin keys are stored at
      // /qxl_keys/{key}, so we don't need an orderByChild query (which
      // would require an `.indexOn` rule in Firebase). This is O(1)
      // and works against any rules configuration.
      const recordRef = ref(getDb(), `qxl_keys/${cleanedKey}`)
      const snap = await get(recordRef)

      if (!snap.exists()) {
        setActivationError(t("activate.form.qxlKey.errorNotFound"))
        setSubmitting(false)
        return
      }

      const record = snap.val() as {
        status?: string
        tier?: string
        keyType?: "one_time" | "no_limit" | "limited"
        userLimit?: number
        usageCount?: number
        usedBy?: { fullName?: string; username?: string }
        accessToken?: string
      }
      const status = String(record.status ?? "unused")
      const tier = asTier(record.tier)
      const keyType = record.keyType ?? "one_time"
      const userLimit =
        typeof record.userLimit === "number" ? record.userLimit : 0
      const usageCount =
        typeof record.usageCount === "number" ? record.usageCount : 0

      // ----- Reuse-policy gate -----
      // For multi-use keys ("no_limit" / "limited") status="used" is
      // only fatal if the cap is exhausted; otherwise we let new
      // users activate as long as the key is still alive.
      if (status === "used") {
        const sameUser =
          record.usedBy?.username?.trim().toLowerCase() ===
          cleanedUser.toLowerCase()

        if (keyType === "one_time" && !sameUser) {
          // Different username = someone else's key. Refuse without
          // revealing who claimed it.
          setActivationError(t("activate.form.qxlKey.errorClaimed"))
          setSubmitting(false)
          return
        }
        if (keyType === "limited" && !sameUser && usageCount >= userLimit) {
          // Cap reached → refuse like a one-time key.
          setActivationError(t("activate.form.qxlKey.errorClaimed"))
          setSubmitting(false)
          return
        }

        // Same username re-submitting from a new browser → mint a
        // fresh token + deviceId, point the qxl_keys row at it, and
        // delete the previous token row so the old browser stops
        // resolving. Falls through into the shared "issue token"
        // block below. We intentionally only do this for the *same*
        // user — multi-use activations from different users keep
        // their own access_tokens rows untouched.
        if (sameUser && record.accessToken && record.accessToken !== "") {
          // Best-effort cleanup; failure here just leaves a stale row.
          await set(
            ref(getDb(), `access_tokens/${record.accessToken}`),
            null,
          ).catch(() => undefined)
        }
      }

      // ------- Issue a fresh session credential -------
      const accessToken = generateAccessToken(tier)
      const deviceId = generateDeviceId()
      const userAgent =
        typeof navigator !== "undefined" ? navigator.userAgent : ""

      // 1) Server-of-truth token row — page client validates against
      //    this. Setting `null` for any field would be rejected by
      //    Firebase, so we always supply concrete values.
      await set(ref(getDb(), `access_tokens/${accessToken}`), {
        token: accessToken,
        qxlKey: cleanedKey,
        deviceId,
        tier,
        fullName: cleanedName,
        username: cleanedUser,
        activatedAt: serverTimestamp(),
        userAgent,
      })

      // 2) Mark the QXL key used (or re-anchor to the new token).
      //    For multi-use keys we increment `usageCount` and only flip
      //    status="used" when the cap is exhausted.
      const sameUser =
        record.usedBy?.username?.trim().toLowerCase() ===
        cleanedUser.toLowerCase()
      const isNewActivation = status !== "used" || !sameUser
      const nextUsage = isNewActivation ? usageCount + 1 : usageCount
      const reachedCap =
        keyType === "limited" ? nextUsage >= userLimit : keyType === "one_time"
      const nextStatus: "used" | "unused" =
        reachedCap || keyType === "one_time" ? "used" : "unused"

      await update(recordRef, {
        status: nextStatus,
        usedBy: { fullName: cleanedName, username: cleanedUser },
        usedAt: serverTimestamp(),
        accessToken,
        deviceId,
        usageCount: nextUsage,
      })

      // 3) Persist the session in this browser so middleware + page
      //    client recognise the visitor on the redirect.
      writeClientSession({ token: accessToken, deviceId, qxlKey: cleanedKey })

      setSuccess({
        name: cleanedName,
        username: cleanedUser,
        qxlKey: cleanedKey,
        accessToken,
      })
    } catch (err) {
      console.log("[v0] activation lookup failed:", err)
      setActivationError(t("activate.form.qxlKey.errorNetwork"))
    } finally {
      setSubmitting(false)
    }
  }

  // Once activation succeeds, give the user a short celebratory beat
  // and then forward them to their personal dashboard. The dashboard
  // is also the launchpad for the four signal rooms. We use the
  // freshly-minted access token (NOT the QXL key) in the URL so that
  // a) the token is uniquely tied to this browser, and b) the user's
  // QXL key never appears in URLs and can't be inferred from links.
  useEffect(() => {
    if (!success) return
    const id = window.setTimeout(() => {
      router.push(`/profile/${encodeURIComponent(success.accessToken)}`)
    }, 1600)
    return () => window.clearTimeout(id)
  }, [success, router])

  const nameCount = fullName.trim().length
  const userCount = username.length
  // Required-field hint takes precedence so the user sees it as soon as
  // they blur an empty field. Once they type, the server-side error
  // (key not found / claimed / network) takes over.
  const qxlKeyError =
    touched.qxlKey && qxlKey.trim().length === 0
      ? t("activate.form.qxlKey.errorRequired")
      : activationError

  return (
    <div className="relative">
      {/* Subtle gradient ring frame — gives the card the "membership pass" feel */}
      <div
        aria-hidden
        className="pointer-events-none absolute -inset-px rounded-[1.6rem] bg-gradient-to-b from-[#5BC0D8]/30 via-[#1B7892]/15 to-transparent"
      />

      <div className="relative overflow-hidden rounded-[1.5rem] border border-[#1B7892]/35 bg-gradient-to-b from-[#04212A] via-[#031C24] to-[#02161D] p-6 backdrop-blur-md sm:p-8 lg:p-10">
        {/* Top accent strip */}
        <span
          aria-hidden
          className="pointer-events-none absolute inset-x-0 top-0 h-[2px] bg-gradient-to-r from-transparent via-[#5BC0D8]/70 to-transparent"
        />
        {/* Corner accents — luxury card vibe */}
        <CornerAccent position="tl" />
        <CornerAccent position="tr" />
        <CornerAccent position="bl" />
        <CornerAccent position="br" />

        {/* Membership ribbon — serial-style header */}
        <div className="relative mb-6 flex items-center justify-between gap-3 border-b border-dashed border-[#1B7892]/35 pb-5 sm:mb-7">
          <div className="flex min-w-0 items-center gap-3">
            <span className="relative flex size-11 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-[#5BC0D8]/30 via-[#1B7892]/30 to-[#03161B]/60 text-[#7DE3FF] ring-1 ring-inset ring-[#5BC0D8]/45 shadow-[inset_0_1px_0_rgba(125,227,255,0.22)]">
              <BadgeCheck className="size-5" aria-hidden strokeWidth={2.2} />
              <span
                aria-hidden
                className="absolute -right-0.5 -top-0.5 size-2 rounded-full bg-[#7DE3FF] shadow-[0_0_8px_rgba(125,227,255,0.7)] motion-safe:animate-pulse"
              />
            </span>
            <div className="flex min-w-0 flex-col gap-0.5">
              <h3 className="font-display text-[19px] tracking-wide text-[#E8F4F7] sm:text-[22px]">
                {t("activate.form.title")}
              </h3>
              <p className="truncate text-[12.5px] font-light leading-snug text-[#E8F4F7]/65 sm:text-[13.5px]">
                {t("activate.form.subtitle")}
              </p>
            </div>
          </div>
        </div>

        {success ? <SuccessOverlay t={t} /> : null}

        <form
          onSubmit={handleSubmit}
          className="flex flex-col gap-5"
          noValidate
          aria-hidden={success ? true : undefined}>
            {/* Full Name */}
            <FormField
              id="fullName"
              icon={<IdCard className="size-[18px]" aria-hidden strokeWidth={1.8} />}
              label={t("activate.form.fullName.label")}
              counter={`${nameCount}/${FULL_NAME_MAX}`}
              counterTone={
                nameCount === 0
                  ? "muted"
                  : nameCount < FULL_NAME_MIN || nameCount > FULL_NAME_MAX
                  ? "danger"
                  : "ok"
              }
              error={touched.fullName ? errors.fullName : null}
            >
              <input
                id="fullName"
                name="fullName"
                type="text"
                value={fullName}
                onChange={(e: ChangeEvent<HTMLInputElement>) =>
                  setFullName(e.target.value)
                }
                onBlur={() => setTouched((s) => ({ ...s, fullName: true }))}
                maxLength={FULL_NAME_MAX}
                placeholder={t("activate.form.fullName.placeholder")}
                autoComplete="name"
                className={inputClass(touched.fullName && !!errors.fullName)}
              />
            </FormField>

            {/* Username — AtSign icon for unique identity */}
            <FormField
              id="username"
              icon={
                <AtSign className="size-[18px]" aria-hidden strokeWidth={1.8} />
              }
              label={t("activate.form.username.label")}
              counter={`${userCount}/${USERNAME_MAX}`}
              counterTone={
                userCount === 0
                  ? "muted"
                  : userCount < USERNAME_MIN ||
                    userCount > USERNAME_MAX ||
                    !USERNAME_RE.test(username)
                  ? "danger"
                  : "ok"
              }
              error={touched.username ? errors.username : null}
            >
              <input
                id="username"
                name="username"
                type="text"
                value={username}
                onChange={(e: ChangeEvent<HTMLInputElement>) => {
                  const next = e.target.value
                  if (next.length === 0 || USERNAME_RE.test(next)) {
                    setUsername(next)
                  }
                }}
                onBlur={() => setTouched((s) => ({ ...s, username: true }))}
                maxLength={USERNAME_MAX}
                placeholder={t("activate.form.username.placeholder")}
                autoComplete="username"
                spellCheck={false}
                className={inputClass(touched.username && !!errors.username)}
              />
            </FormField>

            {/* QXL Key — KeySquare icon (architectural / premium feel) */}
            <FormField
              id="qxlKey"
              icon={
                <KeySquare className="size-[18px]" aria-hidden strokeWidth={1.8} />
              }
              label={t("activate.form.qxlKey.label")}
              error={qxlKeyError}
            >
              <input
                id="qxlKey"
                name="qxlKey"
                type="text"
                value={qxlKey}
                onChange={(e: ChangeEvent<HTMLInputElement>) => {
                  setQxlKey(e.target.value)
                  // Stale server-side error should clear as soon as the
                  // user edits the value — it no longer applies.
                  if (activationError) setActivationError(null)
                }}
                onBlur={() => setTouched((s) => ({ ...s, qxlKey: true }))}
                placeholder={t("activate.form.qxlKey.placeholder")}
                spellCheck={false}
                autoComplete="off"
                className={cn(
                  inputClass(!!qxlKeyError),
                  "font-mono tracking-[0.12em]",
                )}
              />
            </FormField>

            {/* Submit — luxury teal pill with continuous shine + pulse */}
            <button
              type="submit"
              disabled={submitting}
              className="group relative mt-3 inline-flex h-13 w-full items-center justify-center overflow-hidden rounded-xl font-semibold tracking-[0.01em] text-[#03161B] cta-pulse transition-transform duration-300 hover:-translate-y-0.5 active:translate-y-0 disabled:cursor-not-allowed disabled:opacity-70 sm:h-14"
              style={{
                background:
                  "linear-gradient(135deg, #7DE3FF 0%, #5BC0D8 35%, #2EA5C0 65%, #1B7892 100%)",
              }}
            >
              <span
                aria-hidden
                className="pointer-events-none absolute inset-x-0 top-0 h-1/2 bg-gradient-to-b from-white/45 to-transparent"
              />
              <span
                aria-hidden
                className="pointer-events-none absolute inset-x-0 bottom-0 h-1/3 bg-gradient-to-t from-[#0A1A22]/15 to-transparent"
              />
              <span
                aria-hidden
                className="cta-shine pointer-events-none absolute inset-y-0 left-0 w-1/2 bg-gradient-to-r from-transparent via-white/65 to-transparent"
              />
              <span className="relative flex items-center justify-center gap-2.5 px-6">
                {submitting ? (
                  <>
                    <Loader2 className="size-4 shrink-0 animate-spin" strokeWidth={2.5} />
                    <span className="text-[14.5px] sm:text-[15.5px]">
                      {t("activate.form.submitting")}
                    </span>
                  </>
                ) : (
                  <>
                    <span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-[#03161B]/85 text-[#7DE3FF] shadow-[0_0_0_1px_rgba(255,255,255,0.22)_inset]">
                      {/* Unlock — activating successfully unlocks access;
                          pairs naturally with the KeySquare icon used in
                          the QXL Key field above. */}
                      <Unlock className="size-3.5" strokeWidth={2.5} />
                    </span>
                    <span className="text-[14.5px] sm:text-[15.5px]">
                      {t("activate.form.submit")}
                    </span>
                    <ArrowRight
                      className="size-4 shrink-0 transition-transform duration-300 group-hover:translate-x-1"
                      strokeWidth={2.5}
                    />
                  </>
                )}
              </span>
            </button>
          </form>
      </div>
    </div>
  )
}

/* -------------------------------------------------------------------------- */
/*  Internals                                                                 */
/* -------------------------------------------------------------------------- */

function inputClass(hasError: boolean) {
  return cn(
      "w-full rounded-xl border bg-[#02141A]/85 px-3.5 py-3.5 pl-11 text-[14.5px] text-[#E8F4F7] placeholder:text-[#E8F4F7]/30",
    "transition-all duration-200 outline-none shadow-[inset_0_1px_0_rgba(255,255,255,0.04),inset_0_-2px_8px_rgba(0,0,0,0.35)]",
    "focus:bg-[#03171E]",
    hasError
      ? "border-rose-400/60 ring-2 ring-rose-400/15 focus:border-rose-400/80"
      : "border-[#1B7892]/45 focus:border-[#5BC0D8]/75 focus:ring-2 focus:ring-[#5BC0D8]/25",
  )
}

type CounterTone = "muted" | "ok" | "danger"

function FormField({
  id,
  icon,
  label,
  counter,
  counterTone = "muted",
  error,
  children,
}: {
  id: string
  icon: React.ReactNode
  label: string
  counter?: string
  counterTone?: CounterTone
  error: FieldError
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <div className="flex items-center justify-between">
        <label
          htmlFor={id}
          className="text-[11px] font-bold uppercase tracking-[0.22em] text-[#E8F4F7]/85"
        >
          {label}
        </label>
        {counter && (
          <span
            className={cn(
              "font-mono text-[11px] tabular-nums",
              counterTone === "ok" && "text-[#5BC0D8]",
              counterTone === "danger" && "text-rose-400",
              counterTone === "muted" && "text-[#E8F4F7]/40",
            )}
          >
            {counter}
          </span>
        )}
      </div>

      {/* Input + simple icon pinned inside */}
      <div className="relative">
        <span
          aria-hidden
          className="pointer-events-none absolute left-3.5 top-1/2 flex -translate-y-1/2 items-center justify-center text-[#7DE3FF]/85"
        >
          {icon}
        </span>
        {children}
      </div>

      {error && (
        <p className="text-[12px] leading-snug text-rose-400">{error}</p>
      )}
    </div>
  )
}

function CornerAccent({
  position,
}: {
  position: "tl" | "tr" | "bl" | "br"
}) {
  const map: Record<typeof position, string> = {
    tl: "left-3 top-3 border-l-2 border-t-2 rounded-tl-[8px]",
    tr: "right-3 top-3 border-r-2 border-t-2 rounded-tr-[8px]",
    bl: "left-3 bottom-3 border-l-2 border-b-2 rounded-bl-[8px]",
    br: "right-3 bottom-3 border-r-2 border-b-2 rounded-br-[8px]",
  }
  return (
    <span
      aria-hidden
      className={cn(
        "pointer-events-none absolute size-4 border-[#5BC0D8]/55",
        map[position],
      )}
    />
  )
}

/**
 * Activation success overlay. Renders a full-card blurred backdrop above
 * the credentials form so the form fades behind frosted glass while we
 * auto-redirect the user to their dashboard. Intentionally minimal —
 * just the confirmation icon, "Activation complete" title, and an
 * inline "Redirecting to your dashboard…" hint with a spinner. No
 * dashboard CTA button: the parent already pushes the user to
 * /profile/{token} after ~1.6s.
 */
function SuccessOverlay({ t }: { t: (key: string) => string }) {
  return (
    <div
      role="status"
      aria-live="polite"
      className="absolute inset-0 z-20 flex items-center justify-center rounded-[1.5rem] bg-[#02161D]/55 px-6 py-8 backdrop-blur-xl backdrop-saturate-150"
    >
      {/* Soft inner ring so the overlay feels framed by the card */}
      <span
        aria-hidden
        className="pointer-events-none absolute inset-0 rounded-[1.5rem] ring-1 ring-inset ring-[#5BC0D8]/20"
      />
      {/* Subtle top accent line — echoes the card's own accent strip */}
      <span
        aria-hidden
        className="pointer-events-none absolute inset-x-10 top-0 h-px bg-gradient-to-r from-transparent via-[#7DE3FF]/55 to-transparent"
      />

      <div className="relative flex flex-col items-center gap-5 text-center">
        <span className="relative flex size-16 items-center justify-center rounded-full bg-gradient-to-br from-[#5BC0D8]/35 via-[#1B7892]/35 to-[#03161B]/60 text-[#7DE3FF] ring-1 ring-inset ring-[#5BC0D8]/45 shadow-[inset_0_1px_0_rgba(125,227,255,0.22)]">
          <CheckCircle2 className="size-8" aria-hidden strokeWidth={2.2} />
          <span
            aria-hidden
            className="absolute -inset-1 rounded-full ring-1 ring-[#5BC0D8]/25 motion-safe:animate-pulse"
          />
        </span>

        <h4 className="font-display text-[20px] tracking-wide text-[#E8F4F7] sm:text-[24px]">
          {t("activate.form.success.title")}
        </h4>

        <p className="flex items-center gap-2 text-[11.5px] uppercase tracking-[0.22em] text-[#E8F4F7]/55">
          <Loader2 className="size-3.5 animate-spin text-[#5BC0D8]/80" aria-hidden />
          {t("activate.form.success.redirecting")}
        </p>
      </div>
    </div>
  )
}
